### ISSUE TITLE
Uncaught TypeError: Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by samiel60** [liuderchi/atom-i18n#129]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.13.2

### Stack Trace

Uncaught TypeError: Cannot set property 'textContent' of null

```
At /home/samiel/.atom/packages/atom-i18n/lib/welcome.js:47

TypeError: Cannot set property 'textContent' of null
    at Function.updateWelcome (/packages/atom-i18n/lib/welcome.js:47:50)
    at setTimeout (/packages/atom-i18n/lib/welcome.js:59:38)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.13.2 
```

**Comment by samiel60** [comment]
I'm sorry, still not working:

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.13.2


### Stack Trace

Uncaught TypeError: Cannot set property 'textContent' of null

```
At /home/samiel/.atom/packages/atom-i18n/lib/welcome.js:47

TypeError: Cannot set property 'textContent' of null
    at Function.updateWelcome (/packages/atom-i18n/lib/welcome.js:47:50)
    at setTimeout (/packages/atom-i18n/lib/welcome.js:59:38)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.13.2 
```
```

**Comment by liuderchi** [comment]
@samiel60 it's fine 👍 and thanks for taking care of this issue.

This is actually a follow up bug after #80
Will fix it right away 😄

**Comment by samiel60** [comment]
On martedì 2 gennaio 2018 15:17:44 CET Te-Chi Liu wrote:
> @samiel60 it's fine 👍 and thanks for taking care of this issue.
> 
> This is actually a follow up bug after #80
> Will fix it right away 😄


thanx to u for working to solve this bug!

ms

**Comment by liuderchi** [comment]
@samiel60 please install latest patch `v0.13.3` and try it again 💻

**Comment by samiel60** [comment]
On martedì 2 gennaio 2018 07:28:51 CET Te-Chi Liu wrote:
> @samiel60 please install latest patch `v0.13.3` and try it again 💻

now working!!
thanx a lot!

PS
do u think will it be possible to translate
not only the menu, but all the texts of application?
I can help u if u need someone working...

**Comment by liuderchi** [comment]
> do u think will it be possible to translate
> not only the menu, but all the texts of application?

Considering Atom's architecture, it's a *huge challenge* 😓  to translate them all
since quite much content is hard coded in English and dynamic. (see #5 for more info)

But for some part it's technically possible, 
like the style guide and right part of the welcome message.
You are welcomed to suggest by [creating an issue][newissue] if you found some part of it interesting. 👍 

[newissue]: https://github.com/liuderchi/atom-i18n/issues/new "newissue"
