### ISSUE TITLE
Turkish Language Folder 

### ISSUE THREAD

**Issue by Apsimati** [liuderchi/atom-i18n#147]
Please help translate: Turkish.

locale code: `tr`
[locale code table](http://www.science.co.il/language/Codes.php)

files Required translation:
  - `def/ENTER_LOCALE_HERE/about.cson`
  - `def/ENTER_LOCALE_HERE/context.cson`
  - `def/ENTER_LOCALE_HERE/menu_darwin.cson`
  - `def/ENTER_LOCALE_HERE/menu_linux.cson`
  - `def/ENTER_LOCALE_HERE/menu_win32.cson`
  - `def/ENTER_LOCALE_HERE/settings.cson`
  - `def/ENTER_LOCALE_HERE/welcome.cson`

* for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by Apsimati** [comment]
If you add tr folder I can translate it

**Comment by liuderchi** [comment]
@Apsimati Thanks for taking care of Turkish translation 👍 

Please follow issue #83 for more information.
If you find any difficulties with contributing please let me know.

Will close this duplicated issue.
