### ISSUE TITLE
Finnish

### ISSUE THREAD

**Issue by an7oine** [liuderchi/atom-i18n#151]
Please help translate: .

locale code: `fi`
[locale code table](http://www.science.co.il/language/Codes.php)

files Required translation:
  - `def/fi/about.cson`
  - `def/fi/context.cson`
  - `def/fi/menu_darwin.cson`
  - `def/fi/menu_linux.cson`
  - `def/fi/menu_win32.cson`
  - `def/fi/settings.cson`
  - `def/fi/welcome.cson`

* for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by liuderchi** [comment]
@an7oine thanks for creating this issue!
Please feel free to ask anything about joining translation 🎉

**Comment by liuderchi** [comment]
NOTE: TODO for myself

- [ ] add @an7oine to CODEOWNER, contributor list in README.md
- [ ] not preserve bracket in template as defaults
- [ ] prepare v0.14.0 release

**Comment by liuderchi** [comment]
@an7oine Finnish translation has been shipped in [v0.14.0](https://atom.io/packages/atom-i18n) 🎉
