### ISSUE TITLE
No checkbox at welcome screen

### ISSUE THREAD

**Issue by nolt** [liuderchi/atom-i18n#156]
I've noticed that when I switch to translated layout, check box at welcome screen is missing. Check box is used to disable welcome screen on startup. Screen attached.

![zrzut ekranu z 2018-03-08 16-02-29](https://user-images.githubusercontent.com/6367933/37158849-aaba2892-22ec-11e8-9645-d12971404bb4.png)

**Comment by LorenzoAncora** [comment]
Hello @nolt, this is a bug of `atom-i18n`.
To manually disable the welcome screen for all languages, append:

`welcome:`
&nbsp;&nbsp;&nbsp;&nbsp;`showOnStartup: false`

...to `~/.atom/config.cson`.

**Comment by nolt** [comment]
Yes I know, but still it's a manual resolve. Someone who will run Atom first time can disable it on default translation so bug is not visible anymore but still exist.

**Comment by LorenzoAncora** [comment]
Hello @nolt, I agree: I do not like manual solutions in GUI apps, too.
Since @liuderchi inserted the 'help wanted' tag I've just written and submitted a little patch (patch #158) to resolve the bug. ;-)

**Comment by nolt** [comment]
Hi @LorenzoAncora thanks for the quick fix :)

**Comment by liuderchi** [comment]
@nolt @LorenzoAncora Thanks for your great help. 💯 
Will release a patch for bug fixes recently.

**Comment by LorenzoAncora** [comment]
@nolt merging was a bit cumbersome due to the various GitHub branches, but now the bugfix has been inserted directly into the main branch. Wait for the update (recommended) or clone the sources.
If you find other problems do not hesitate to report them.

@nolt @liuderchi see you next time. :-)
