### ISSUE TITLE
Half transladed menu on right click

### ISSUE THREAD

**Issue by nolt** [liuderchi/atom-i18n#157]
Bug present when I right click on tree list, translation looks like it is half completed.
I tried to search in translation or template but didn' found anything releaded to this menu.

I use Atom on Linux (Ubuntu 17.10), don't know if bug is present on Windows, maybe can someone test it on his translation?
Image attached
![zrzut ekranu z 2018-03-09 15-21-06](https://user-images.githubusercontent.com/6367933/37212075-4f2084e6-23ae-11e8-99bb-add40dea8614.png)

**Comment by Umoxfo** [comment]
A `selector` definition of the tree-view context menu is different from the original.
[https://github.com/atom/tree-view/blob/master/menus/tree-view.cson](https://github.com/atom/tree-view/blob/master/menus/tree-view.cson)
