### ISSUE TITLE
Belarusian translation

### ISSUE THREAD

**Issue by antikruk** [liuderchi/atom-i18n#178]
Hi, add, please, Belarusian translation
[Belarusian.zip](https://github.com/liuderchi/atom-i18n/files/2041963/Belarusian.zip)

**Comment by liuderchi** [comment]
@antikruk Would you like to create pull request follow [contribution guide](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)?
Only with that can we add your contribution into the commit history

**Comment by antikruk** [comment]
Ok
