### ISSUE TITLE
Element duplicate

### ISSUE THREAD

**Issue by antikruk** [liuderchi/atom-i18n#180]
Hi, help me, please. In the Belarusian translation the element is duplicated
![2018-05-29_23-14-07](https://user-images.githubusercontent.com/6292989/40683161-598e1da8-6396-11e8-84ae-a9079e67db49.png)

**Comment by antikruk** [comment]
There are no rows in the file menu_linux.cson : 
- Paste without reformatting
- Toogle Git Tab 
- Toogle GitHub Tab 
- View Unstaged Changes
- View Staged Changes
- Select to Next Bookmark
- Select to Previous Bookmark
In settings:
- Use Tree Siter Parsers with description
-Url Handling Tab

**Comment by liuderchi** [comment]
@antikruk First comment has been issued in #86. It's been patched with workaround.
More solid solution is wanting.

---

> There are no rows in the file menu_linux.cson :

Do you mean some menu items is not translated?
If so, this package require an update once this menu item is from Atom Official Package.

**Comment by antikruk** [comment]
> @antikruk First comment has been issued in #86. It's been patched with workaround.
More solid solution is wanting.

Ok

**Comment by antikruk** [comment]
> Do you mean some menu items is not translated?
If so, this package require an update once this menu item is from Atom Official Package.

It is really welcomed to discuss it in another new issue.
Yes, exactly. Create it here or in Atom repo?

**Comment by liuderchi** [comment]
@antikruk create it here.
