### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetParent' of null

### ISSUE THREAD

**Issue by admin-lm** [liuderchi/atom-i18n#196]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.14
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.16.0

### Stack Trace

Uncaught TypeError: Cannot read property 'offsetParent' of null

```
At /Users/leon/.atom/packages/atom-i18n/lib/about.js:34

TypeError: Cannot read property 'offsetParent' of null
    at Function.updateAbout (/packages/atom-i18n/lib/about.js:34:24)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.16.0 
```

**Comment by lingruby-pl** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.12
**OS**: "Arch Linux"
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.16.0


### Stack Trace

Uncaught TypeError: Cannot read property 'offsetParent' of null

```
At /home/lingruby/.atom/packages/atom-i18n/lib/about.js:34

TypeError: Cannot read property 'offsetParent' of null
    at Function.updateAbout (/packages/atom-i18n/lib/about.js:34:24)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-i18n 0.16.0 
color-picker 2.3.0 
filetype-color 0.1.4 
native-color-picker 0.2.5 
```

**Comment by LorenzoAncora** [comment]
@lingruby-pl @admin-lm
Don't worry, it is not a problem that can compromise the functionality of Atom. I take care of the problem with the following pull request. ;-)

You can continue to use the editor without fear, taking care to install the next atom-i18n update when it is available.

Have a good day. :-)

**Comment by liuderchi** [comment]
thanks for all your contribution and it's released as __v0.16.3__
