### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by RealA10N** [liuderchi/atom-i18n#224]
Please help translate:

locale code: `he`
[locale code table](http://www.science.co.il/language/Codes.php)

files Required translation:
  - `def/he/about.cson`
  - `def/he/context.cson`
  - `def/he/menu_darwin.cson`
  - `def/he/menu_linux.cson`
  - `def/he/menu_win32.cson`
  - `def/he/settings.cson`
  - `def/he/welcome.cson`

* for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by liuderchi** [comment]
@RealA10N [atom-i18n v0.20](https://atom.io/packages/atom-i18n) has released and please try it 🎉
