### ISSUE TITLE
I want to help translate atom into Swedish

### ISSUE THREAD

**Issue by Umeaboy** [liuderchi/atom-i18n#242]
Please help translate: .

locale code: `sv_SE`
[locale code table](http://www.science.co.il/language/Codes.php)

files Required translation:
  - `def/sv_SE/about.cson`
  - `def/sv_SE/context.cson`
  - `def/sv_SE/menu_darwin.cson`
  - `def/sv_SE/menu_linux.cson`
  - `def/sv_SE/menu_win32.cson`
  - `def/sv_SE/settings.cson`
  - `def/sv_SE/welcome.cson`

* for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by liuderchi** [comment]
@Umeaboy Thanks for caring Swedish translation!
Please refer to #216 for more info. Feel free to discuss if you have any questions.
