### ISSUE TITLE
Can not localize Welcome-view

### ISSUE THREAD

**Issue by juggernautjp** [liuderchi/atom-i18n#297]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>, <atom-i18n; https://github.com/liuderchi/atom-i18n/issues>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
"Welcome" view is not localized.

### Steps to Reproduce

1. Click "Settings" in "File" menu
2. Click "Packages" in "Settings" view
3. Click "Enable" in "atom-i18n" package
4. Click "Settings" of the "atom-i18n" package
5. Set "Language" to "???(ja)" in the list
6. Click "Welcome" in "Help" menu
7. "Welcome" view is appeared

**Expected behavior:**
Some English words in "Welcome" view and sentences are localized.

**Actual behavior:**
"Welcome" view has some English words.

**Reproduces how often:**
Always

### Versions
```
- Atom    : 1.55.0
- Electron: 6.1.12
- Chrome  : 76.0.3809.146
- Node    : 12.4.0
```

### Additional Information
![image](https://user-images.githubusercontent.com/56490448/111868975-5bb13b80-89c0-11eb-8ce8-5251c0a17abd.png)

### TODO

- The issue [#237](https://github.com/liuderchi/atom-i18n/issues/237) includes this one, but I have already found other issues in atom-i18n.
So, I will issue each bug of atom-i18n, and fix them for a couple of weeks (or months).
- atom-i18n package might be possible to improve performance.

**Comment by liuderchi** [comment]
@juggernautjp Thanks for your contribution! Your fix has been published in `v0.25.1`
https://atom.io/packages/atom-i18n
