### ISSUE TITLE
Translate into Hindi

### ISSUE THREAD

**Issue by liuderchi** [liuderchi/atom-i18n#31]
files require translation:
  - [x] `def/hi/about.cson`
  - [x] `def/hi/context.cson`
  - [x] `def/hi/menu_darwin.cson`
  - [x] `def/hi/menu_linux.cson`
  - [x] `def/hi/menu_win32.cson`
  - [x] `def/hi/settings.cson`

for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by themakerman** [comment]
Hey, i can work on this. Will it be still helpful?

**Comment by liuderchi** [comment]
@themakerman Definitely it is! Thanks for your help 🙏
Please refer to [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md) and let me know if you found any difficulties.

**Comment by themakerman** [comment]
Can u help me assign the status to dev in progress for hindi localization?

**Comment by liuderchi** [comment]
@themakerman OK~

**Comment by themakerman** [comment]
Work in progress:
- [] def/hi/about.cson
- [x] def/hi/context.cson
- [ ] def/hi/menu_darwin.cson
- [ ] def/hi/menu_linux.cson
- [ ] def/hi/menu_win32.cson
- [ ] def/hi/settings.cson

**Comment by liuderchi** [comment]
@themakerman thanks for your help!
Just feel free to create PR at your pace.

**Comment by themakerman** [comment]
Hi @liuderchi localisation is finally done. Would be grateful if you take a look at it and merge :). 
Had one of the contributors: https://github.com/ankitbulchandani to help me out as well. 

Thanks

**Comment by themakerman** [comment]
@liuderchi Also was wondering if i should PR for updating of contributors page and removing 'I can translate' for hi locale

**Comment by liuderchi** [comment]
@themakerman I will do that when release, thanks!

**Comment by themakerman** [comment]
Great @liuderchi Any updates on release schedule you can share? so that i can take a look at it in production package in atom?

**Comment by liuderchi** [comment]
@themakerman atom-i18n has [released `0.23.0` with Hindi support](https://atom.io/packages/atom-i18n), please go check it out! Thanks for your contribution!
