### ISSUE TITLE
Translate into Russian

### ISSUE THREAD

**Issue by firefoxic** [liuderchi/atom-i18n#44]
Файлы, требующие перевода:

- [x]     def/ru/about.cson
- [x]     def/ru/context.cson
- [x]     def/ru/menu_darwin.cson
- [x]     def/ru/menu_linux.cson
- [x]     def/ru/menu_win32.cson
- [x]     def/ru/settings.cson

Для получения дополнительной информации ознакомьтесь с [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by liuderchi** [comment]
@firefoxic too bad I cannot speak Russian.
I feel glad that you cares about translation into Russian. :tada: 

If you would like to contribute, please read *[Steps to Contribute](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md#steps-to-contribute)* and 
copy templates for Russian as described in step 5.

```shell
cd def && cp -r template ru
```

so that you can translate into Russian from English.

**Comment by firefoxic** [comment]
@liuderchi, this issue I have created for Russian-speakers who wish to join the translation. Therefore, in Russian ;-)

Do I need to send a pull request immediately after copying templates `def/ru` directory  to other translators did not have to do this?

**Comment by liuderchi** [comment]
@firefoxic that's also welcome. :smile: 
BTW it would be great if you help *adding Russian option* in [package config](https://github.com/liuderchi/atom-i18n/blob/master/package.json#L75)

**Comment by Anonym0uz** [comment]
Wow, i can help with translation into Russian language :)
Now translated 5-6%.
![2017-03-07 5 13 06](https://cloud.githubusercontent.com/assets/12852616/23638800/d208a9fa-02f4-11e7-9a7d-3092449218e6.png)

**Comment by liuderchi** [comment]
@Anonym0uz Thank you for supporting Russian translation!

It's welcome that you *create a Pull Request first* even you have not finished them.
You don't have to do it all in one step; after all it's a great deal of works. :smiley:

**Comment by liuderchi** [comment]
- [ ] add [Driglu4it](https://github.com/Driglu4it) to README.md after PRs are merged.
