### ISSUE TITLE
Missing keys on ru locale

### ISSUE THREAD

**Issue by stsewd** [liuderchi/atom-i18n#52]
Travis is failing because of new options added on 6d500fc6a09c2fb0dc0600b4f5a25f2d0fbd978a for all locales, except for `ru` locale.

Can we fix this or are we waiting for #50 to be merged?

p.s: Thanks for make me collaborator 😄

**Comment by liuderchi** [comment]
@stsewd thanks for pointing out
I've merged #50 and I will fix it to pass Travis.
