### ISSUE TITLE
Conflict with Atom Stylesheet

### ISSUE THREAD

**Issue by trifirew** [liuderchi/atom-i18n#59]
Atom stylesheet `styles.less` doesn't work in translated page (i.e. Settings).

## Reproduction

Try to change font of Settings UI with `styles.less`
```less
.settings-view {
  font-family: "Trebuchet MS";
}
```

#### Original font: 
![image](https://cloud.githubusercontent.com/assets/22854142/24046442/eb044778-0af8-11e7-9660-43858ff42963.png)

#### After changing (**without** `atom-i18n` installed)
![image](https://cloud.githubusercontent.com/assets/22854142/24046482/14fa0ae0-0af9-11e7-87dc-c27dbc931bb5.png)

#### After changing (**with** `atom-i18n` installed and enabled)
![image](https://cloud.githubusercontent.com/assets/22854142/24046605/7436bab2-0af9-11e7-90ec-e6a433bf85c9.png)
which does not appear to change from original font.

**Comment by liuderchi** [comment]
@trifirew Which platform are you using (win32/linux/darwin)?

**Comment by trifirew** [comment]
@liuderchi win32

**Comment by liuderchi** [comment]
confirmed this behavior results from function call `applyFonts()`
Please hold on and I'll fix it :+1:
