### ISSUE TITLE
Translate into Polish

### ISSUE THREAD

**Issue by Jeplaa** [liuderchi/atom-i18n#71]
files Required translation:
  - `def/pl/about.cson`
  - `def/pl/context.cson`
  - `def/pl/menu_darwin.cson`
  - `def/pl/menu_linux.cson`
  - `def/pl/menu_win32.cson`
  - `def/pl/settings.cson`

* for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by liuderchi** [comment]
@Jeplaa I am so glad that you notice Polish.
It's really welcome to contribute even it's little.

**Comment by liuderchi** [comment]
NOTE for myself:
- [ ] add locale `pl` in `validation.js` after this PR is merged
