### ISSUE TITLE
Translate into Azerbaijani

### ISSUE THREAD

**Issue by ziyaddin** [liuderchi/atom-i18n#78]
Files require translation:
  - [ ] `def/az/about.cson`
  - [ ] `def/az/context.cson`
  - [ ] `def/az/menu_darwin.cson`
  - [ ] `def/az/menu_linux.cson`
  - [ ] `def/az/menu_win32.cson`
  - [ ] `def/az/settings.cson`

For more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by ziyaddin** [comment]
@liuderchi I can help with translation.

**Comment by liuderchi** [comment]
@ziyaddin Thank you so much!

I updated `master` one hour ago with tiny changes to `*.cson`, 
so please update `master` before copying `def/template` to `def/az`

**Comment by liuderchi** [comment]
@ziyaddin What's best way to describe Azerbaijani in Azerbaijani?
I found some options [here](http://www.omniglot.com/writing/azeri.htm).

**Comment by ziyaddin** [comment]
@liuderchi The correct way of

- `Azerbaijani language` is `Azərbaycan dili`
- `Azerbaijani` is `Azərbaycanca`
