### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by ghost** [liuderchi/atom-i18n#80]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.8.0

### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of null

```
At /home/clsalberto/.atom/packages/atom-i18n/lib/welcome.coffee:22

TypeError: Cannot set property 'innerHTML' of null
    at Welcome.updateWelcome (/packages/atom-i18n/lib/welcome.coffee:22:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.8.0 
atom-less 0.1.10 
atom-sass 0.4.0 
atom-save-all 0.4.1 
language-blade 0.29.0 
language-ini 1.19.0 
language-pgsql 0.2.3 
laravel 0.7.1 
minimap 4.27.1 
minimap-find-and-replace 4.5.2 
trailing-spaces 0.4.0 
```

**Comment by liuderchi** [comment]
@clsalberto thanks for pointing out this issue :+1: 

Please help with the following questions to reproduce this behavior.
1. How often does this happen?
2. What's your locale setting?
3. Did you check the option *Show Welcome Guide when opening Atom* in welcome page ?

**Comment by sitdh** [comment]
I found this error too,

1. Always when I open apps
2. TH
3. Yes

**Error trace below**

[Enter steps to reproduce:]

1. With default Atom setting, Install the package _[Show Welcome Guide checked]_
1. Open Atom, Error window will display
1. Click another tab, Another error window display again

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.11.0


### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of null

```
At /Users/sitdh/Projects/contribute/atom-i18n/lib/welcome.coffee:22

TypeError: Cannot set property 'innerHTML' of null
    at Welcome.updateWelcome (/Users/sitdh/Projects/contribute/atom-i18n/lib/welcome.coffee:22:7)
```

### Commands

```
  6x -1:51 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-i18n 0.11.0 
vim-mode 0.66.0 
```

**Comment by wingsofovnia** [comment]
I'm experiencing the same error for the `template` translation.

**Comment by liuderchi** [comment]
@wingsofovnia is it happening with just opened *Welcome* tab opened by Atom?

It would be nice if you may provide error message or additional info to help me reproduce it.

**Comment by uzielweb** [comment]
Same error for me. My Atom is the latest version.

**Comment by samiel60** [comment]
In a fresh installation on Debian Testing, today, I received the same error
ms

**Comment by samiel60** [comment]
If it's relevant, I set Italian language. The same in LinuxMint, just now. Backtrace is:
=========================================================================
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.13.0


### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of null

```
At /home/samiel/.atom/packages/atom-i18n/lib/welcome.coffee:22

TypeError: Cannot set property 'innerHTML' of null
    at Welcome.updateWelcome (/packages/atom-i18n/lib/welcome.coffee:22:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.13.0 
```
=========================================================================

**Comment by samiel60** [comment]
I tried other languages, as Franch. All goes. The error appears only if I select Italian as language for Atom

**Comment by liuderchi** [comment]
@samiel60 thanks for your investigation. I'm working on fixing it

**Comment by samiel60** [comment]
is the correct version now available? for I download again the file, installed the l18n package, but I receive the same error...

**Comment by liuderchi** [comment]
@samiel60 I just published a patch release v0.13.1
please upgrade and try it again.

**Comment by samiel60** [comment]
I downloaded l18n 31.1, but I receive the same error :(

**Comment by liuderchi** [comment]
@samiel60 would you please provide the error message?

**Comment by samiel60** [comment]
I downloaded again and reinstall cleanly atom. I addes the nwe language pack and tried to set Atom in Italian. After reload:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.13.1


### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of null

```
At /home/samiel/.atom/packages/atom-i18n/lib/welcome.js:18

TypeError: Cannot set property 'innerHTML' of null
    at Function.updateWelcome (/packages/atom-i18n/lib/welcome.js:18:30)
    at setTimeout (/packages/atom-i18n/lib/welcome.js:59:38)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.13.1 
```

**Comment by liuderchi** [comment]
@samiel60 thanks for your help 🙏 
Please download latest patch version v0.13.2 and try it again.

**Comment by samiel60** [comment]
Yet not working :(
`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.13.2


### Stack Trace

Uncaught TypeError: Cannot set property 'textContent' of null

```
At /home/samiel/.atom/packages/atom-i18n/lib/welcome.js:47

TypeError: Cannot set property 'textContent' of null
    at Function.updateWelcome (/packages/atom-i18n/lib/welcome.js:47:50)
    at setTimeout (/packages/atom-i18n/lib/welcome.js:59:38)
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.13.2 
```

`
