### ISSUE TITLE
Translate into Polish

### ISSUE THREAD

**Issue by nolt** [liuderchi/atom-i18n#90]
Please help translate: Polish.

locale code: `pl`
[locale code table](http://www.science.co.il/language/Codes.php)

files Required translation:
  - `def/pl/about.cson`
  - `def/pl/context.cson`
  - `def/pl/menu_darwin.cson`
  - `def/pl/menu_linux.cson`
  - `def/pl/menu_win32.cson`
  - `def/pl/settings.cson`
  - `def/pl/welcome.cson`

* for more info please checkout [CONTRIBUTING.md](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md)

**Comment by liuderchi** [comment]
Thanks for contributing 🎉 

TODOS reminder after PR merged
  - [ ] update progress, add contributor to README.md
  - [ ] update pl in validation.js
  - [ ] update CHANGELOG.md

**Comment by liuderchi** [comment]
TODO reminder after PR merged

- update progress in `README.md`

**Comment by liuderchi** [comment]
Progress is updated in `README.md` so will close this issue
