### ISSUE TITLE
Cant preview development package

### ISSUE THREAD

**Issue by nolt** [liuderchi/atom-i18n#91]
Hi,

I cant preview mine development translation. I've follow the guide "How to Preview Your Translation in Development?" but while I link mine fork folder with repository and reload Atom. I don't see mine lanugage in atom-i18n settings.
![zrzut ekranu z 2017-07-05 14-48-40](https://user-images.githubusercontent.com/6367933/27865161-c8319fee-6191-11e7-95b4-98510a701202.png)

**Comment by liuderchi** [comment]
@nolt I missed one important step in [step 5.](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md#steps-to-contribute)
Please insert following 4-line code to [here in package.json](https://github.com/liuderchi/atom-i18n/blob/master/package.json#L74):

```json
{
    "value": "pl",
   "description": "Polski (pl)"
},
```

**Comment by nolt** [comment]
Thanks, now everything works well.
