### ISSUE TITLE
Settings tab resets the language after being reopen

### ISSUE THREAD

**Issue by rogi27** [liuderchi/atom-i18n#97]
After the '**Settings**' tab being reopen it just resets the language back to **English**.
_I'm using a Russian translation for Atom._

Looks like this bug only in Settings tab, because other tabs working fine and didn't reset the lang. Menu items shown on English but title still being on Russian.

**Comment by liuderchi** [comment]
> After ...,  it just resets the language back to English

@sdir01 when it occurred, how did other UI look like? 
For example, did Menu Item shown English (or Russian)?

**Comment by sdir01** [comment]
@liuderchi Looks like this bug only in Settings tab, because other tabs working fine and didn't reset the lang. Menu items shown on English but title still being on Russian.

**Comment by liuderchi** [comment]
I can not reproduce this behavior, but I did sometimes encounter it.
I will keep an eye on this issue and hopefully I can find the root cause.

**Comment by Vivalzar** [comment]
Yes, same thing for me. It happens from time to time but I can't reliably reproduce it.

**Comment by kckbck88** [comment]
Same bug for me too. Nothing new about it?

**Comment by liuderchi** [comment]
@kckbck88 nothing new about it except some little observation.

Last year I switch my atom theme to [atom-material](https://atom.io/users/atom-material) (both ui and syntax) found it produced obvious overhead when showing settings tab.
And sometimes the content in settings tab would disappear for a while.

Perhaps some atom theme may have race condition with atom-i18n.

@kckbck88 What is your atom theme (ui/syntax) and what's your environment? (os, atom version)

**Comment by kckbck88** [comment]
@liuderchi I use Arch Linux, I tried with i3 and with xfce4.
My atom version is 1.23.3, I tried with Atom Dark (ui & synthax) and One Dark (ui & synthax).
In each case it does the bug.
